const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./dist/engine'),F=require('./dist/feedback'),Audio=require('./dist/audio'),app=require('./test-ui.cjs');
let passed=0;function test(name,f){f();passed++;console.log('PASS',name);}
const match=()=>E.create('feedback',100,5,{stage:'beach',sediment:'clay',time:'day',weather:'clear'});
test('Idle and empty clicks do not start turn clock; match clock continues',()=>{const a=app(E.encode(match()));a.advance(1000);assert.equal(a.read().turnRemaining,5);assert(a.read().remaining<100);a.pointer('pointerdown',2,2);a.advance(1000);a.pointer('pointerup',2,2);assert.equal(a.read().turnStarted,false);assert.equal(a.read().turnRemaining,5);assert(a.read().remaining<99);});
test('Actual minimum harvest starts countdown and next player waits again',()=>{const a=app(E.encode(match()));a.choose('needle');a.pointer('pointerdown');assert(a.read().harvest>=.001);assert(a.read().turnStarted);a.advance(400);assert(a.read().turnRemaining<5);a.pointer('pointerup');a.advance(1600);assert.equal(a.read().player,2);assert.equal(a.read().turnStarted,false);assert.equal(a.read().turnRemaining,5);a.advance(500);assert.equal(a.read().turnRemaining,5);});
test('No-harvest pass is blocked in the actual controller',()=>{const a=app(E.encode(match()));a.el('pass').onclick();assert.equal(a.read().player,1);assert(a.el('pass').disabled);});
test('Cancelled harvest restores waiting clock and no score',()=>{const a=app(E.encode(match()));a.pointer('pointerdown');a.advance(100);assert(a.read().turnStarted);a.pointer('pointercancel');assert(!a.read().turnStarted);assert.equal(a.read().turnRemaining,5);assert.equal(a.read().harvest,0);});
test('Waiting clock survives a saved reload',()=>{const a=app(E.encode(match()));a.advance(16000,100);const raw=a.storage.get('sand-digger.save.v3'),b=app(raw);assert.equal(b.read().turnStarted,false);assert.equal(b.read().turnRemaining,5);});
test('Physics off gives all materials common weight and collapse rules',()=>{const states=E.MATERIALS.map(m=>E.create('common',600,45,{sediment:m.id,materialPhysics:false,weather:'rain',stage:'ocean-ship'}));for(const s of states){assert.deepEqual(s.grid,states[0].grid);assert.equal(E.harvestGrams(s,1),.7);assert.equal(E.properties(s).bridge,2);assert.equal(E.properties(s).stress,0);assert.equal(E.properties(s).shake,0);}assert.equal(E.properties(E.create('on',600,45,{sediment:'gravel'})).bridge,0);});
test('Physics checkbox persists and older missing option keeps default on',()=>{const a=app();a.submit({sediment:'clay',materialPhysics:false});assert.equal(a.get().materialPhysics,false);const raw=JSON.parse(E.encode(match()));delete raw.materialPhysics;assert.equal(E.properties(E.decode(JSON.stringify(raw))).bridge,4);for(const field of['materialPhysics','turnStarted'])assert.throws(()=>E.decode(JSON.stringify({...raw,[field]:'false'})));});
test('Eight deterministic surface textures differ without changing physical state',()=>{const signatures=new Set(),s=match(),raw=E.encode(s);for(const material of E.MATERIALS){const t=F.surface(material);assert.equal(t.data.length,48*48*4);signatures.add(Buffer.from(t.data).toString('base64'));assert.deepEqual(t,F.surface(material));}assert.equal(signatures.size,8);assert.equal(E.encode(s),raw);});
test('Cloth follows wind direction and remains anchored along entire pole edge',()=>{const s=match(),f=s.flag,e=E.environment(s),a=F.flagPoint(f,{...e,windDirection:0},2,1,.5),b=F.flagPoint(f,{...e,windDirection:Math.PI},2,1,.5);assert.notDeepEqual(a,b);assert.deepEqual(F.flagPoint(f,e,0,0,.5),F.flagPoint(f,{...e,windStrength:1},4,0,.5));});
test('Strong wind increases flutter and falling cloth stays finite',()=>{const s=match(),f=s.flag,e=E.environment(s);const span=strength=>{let min=Infinity,max=-Infinity;for(let t=0;t<40;t++){const p=F.flagPoint(f,{...e,windDirection:0,windStrength:strength},t/5,1,.5);min=Math.min(min,p[2]);max=Math.max(max,p[2]);}return max-min;};assert(span(1)>span(.1));for(const angle of[0,.3,1,Math.PI/2])for(const direction of[0,Math.PI/2,Math.PI])for(const u of[0,.5,1])assert(F.flagPoint({...f,angle,drop:2}, {...e,windDirection:direction},2,u,.5).every(Number.isFinite));});
test('Fallen flags continue fluttering; reduced motion suppresses oscillation',()=>{const f={...match().flag,angle:Math.PI/2,drop:3},e={...E.environment(match()),windStrength:1};assert.notDeepEqual(F.flagPoint(f,e,1,1,.5),F.flagPoint(f,e,2,1,.5));assert.deepEqual(F.flagPoint(f,e,1,1,.5,true),F.flagPoint(f,e,2,1,.5,true));});
test('Each tool has a distinct use pose and actual drawing path',()=>{const a=app(),signatures=new Set();for(const tool of Object.keys(E.TOOLS)){signatures.add(JSON.stringify(F.pose(tool,.25)));a.choose(tool);a.pointer('pointerdown');a.frame(40);a.pointer('pointercancel');}assert.equal(signatures.size,6);});
test('Material effects emit distinct filtered noise plus tones and respect mute',()=>{
 const events=[];const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}});class Context{constructor(){this.state='running';this.currentTime=0;this.sampleRate=8000;this.destination={};}createGain(){return{gain:param(),connect(){},disconnect(){}};}createOscillator(){return{frequency:param(),connect(){},disconnect(){},start(){events.push(['tone',this.frequency.value,this.type]);},stop(){}};}createBuffer(n,len){return{getChannelData:()=>new Float32Array(len)};}createBufferSource(){return{connect(){},disconnect(){},start(){events.push(['noise']);},stop(){}};}createBiquadFilter(){return{frequency:param(),Q:param(),connect(){events.push(['filter',this.type,this.frequency.value]);},disconnect(){}};}}
 global.AudioContext=Context;try{const audio=new Audio();assert(audio.unlock());const profiles=new Set();for(const m of E.MATERIALS){events.length=0;audio.effect('dig',m.id,'finger');assert(events.some(x=>x[0]==='noise'));profiles.add(JSON.stringify(events));}assert.equal(profiles.size,8);audio.fx=false;const before=events.length;audio.effect('dig','gravel');assert.equal(events.length,before);audio.stop();assert.equal(audio.nodes.size,0);}finally{delete global.AudioContext;}
});
test('Root and generated entry match, toolbar remains bottom and status has top class',()=>{const html=fs.readFileSync(__dirname+'/index.html','utf8'),css=fs.readFileSync(__dirname+'/dist/style.css','utf8');assert(html.includes('arena-bottom top-status'));assert(html.includes('id="materialPhysics"'));assert(html.includes('0.001g'));assert(css.includes('justify-content:space-between;gap:120px'));assert(css.includes('.canvas-tools{bottom:12px}'));assert.equal(html.replace(/((?:src|href)=")dist\//g,'$1'),fs.readFileSync(__dirname+'/dist/index.html','utf8'));});
console.log('\n'+passed+' feedback tests passed. No real-device visual or audio listening checks were performed.');
