const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),E=require('./dist/engine.js');
let passed=0;function test(name,fn){fn();console.log('PASS',name);passed++;}const count=s=>s.grid.reduce((a,b)=>a+b,0);
test('Same seed reproduces terrain and flag',()=>assert.equal(E.encode(E.create('a')),E.encode(E.create('a'))));
test('100 initial seeds stand without collapse',()=>{for(let i=0;i<100;i++){let s=E.create('test'+i);assert.equal(E.flagPlan(s).fall,false);assert.equal(E.settle(s).moved,0);}});
test('Every tool removes real mass within its budget',()=>{for(const tool of Object.keys(E.TOOLS)){let s=E.create(),before=count(s),n=E.carve(s,[12.5,11,12.5],[0,-1,0],tool,E.TOOLS[tool].limit);assert(n>0);assert(n<=E.TOOLS[tool].limit);assert.equal(before-count(s),n);}});
test('Deep dig creates an internal cavity beneath a ceiling',()=>{let s=E.create();s.grid.fill(0);for(let y=0;y<8;y++)for(let z=8;z<17;z++)for(let x=8;x<17;x++)s.grid[E.index(x,y,z)]=1;let n=E.carve(s,[12.5,3.5,8],[0,0,1],'finger',70);assert(n>0);assert.equal(E.get(s.grid,12,3,10),0);assert.equal(E.get(s.grid,12,7,10),1);let raw=E.encode(s);assert.equal(E.get(E.decode(raw).grid,12,3,10),0);});
test('Unsupported ceiling falls, preserving total mass',()=>{let s=E.create();s.grid.fill(0);s.grid[E.index(12,10,12)]=1;let before=count(s);assert(E.settle(s).moved>0);assert.equal(E.get(s.grid,12,0,12),1);assert.equal(count(s),before);});
test('Short supported arch stays over an open tunnel',()=>{let s=E.create();s.grid.fill(0);for(let y=0;y<4;y++){s.grid[E.index(10,y,12)]=1;s.grid[E.index(14,y,12)]=1;}for(let x=10;x<=14;x++)s.grid[E.index(x,3,12)]=1;E.settle(s);assert.equal(E.get(s.grid,12,3,12),1);assert.equal(E.get(s.grid,12,2,12),0);});
test('Repeated input cannot harvest already removed cells',()=>{let s=E.create(),p=[12.5,11,12.5],d=[0,-1,0];E.carve(s,p,d,'brush',999);assert.equal(E.carve(s,p,d,'brush',999),0);});
test('Collapse and same actions are deterministic',()=>{let a=E.create('repeat'),b=E.create('repeat');for(let i=0;i<8;i++)for(let s of[a,b]){E.carve(s,[12,8,12-i/2],[0,-1,0],'hand',100);E.settle(s);}assert.equal(E.encode(a),E.encode(b));});
test('Sway alone does not count as contact',()=>{let s=E.create();assert.equal(E.flagContact(s,.3,0),false);});
test('An unsupported flag can reach actual floor contact',()=>{let s=E.create();s.grid.fill(0);assert(E.flagPlan(s).fall);assert.equal(E.flagContact(s,Math.PI/2,0),false);s.flag.drop=s.flag.root;assert.equal(E.flagContact(s,Math.PI/2,0),true);});
test('KO overrides a higher score and blames current actor',()=>{let s=E.create();s.scores=[900,0];E.endTurn(s,10,true);assert.deepEqual(s.result,{winner:1,reason:'ko',actor:0});});
test('Only harvested mass is scored in tenths of grams',()=>{let s=E.create();E.endTurn(s,3);assert.deepEqual(s.scores,[21,0]);assert.equal(s.player,1);});
test('Expired first move gives second player final reply',()=>{let s=E.create();s.expired=true;s.remaining=0;E.endTurn(s,10);assert.equal(s.result,null);assert.equal(s.player,1);E.endTurn(s,5);assert.equal(s.result.winner,0);});
test('Equal displayed weights produce a draw',()=>{let s=E.create();s.expired=true;E.endTurn(s,10);E.endTurn(s,10);assert.equal(s.result.winner,null);});
test('Result cannot be counted twice',()=>{let s=E.create();E.endTurn(s,12,true);const before=E.encode(s);E.endTurn(s,12,true);assert.equal(E.encode(s),before);});
test('Save roundtrip preserves state including cavities',()=>{let s=E.create();E.carve(s,[12,8,12],[1,0,0],'finger',40);E.endTurn(s,8);assert.equal(E.encode(E.decode(E.encode(s))),E.encode(s));});
test('Invalid saves and old versions rejected without state changes',()=>{let s=E.create(),raw=E.encode(s);for(const bad of['','{}','not json',raw.replace('sand-voxel-1','sand-voxel-0'),JSON.stringify({...JSON.parse(raw),scores:[-1,0]}),JSON.stringify({...JSON.parse(raw),grid:[2]}),JSON.stringify({...JSON.parse(raw),flag:{...s.flag,drop:-1}})])assert.throws(()=>E.decode(bad));assert.equal(E.encode(s),raw);});
test('Invalid settings and carving inputs are rejected',()=>{assert.throws(()=>E.create('',600,45));assert.throws(()=>E.create('x',-2,45));assert.throws(()=>E.carve(E.create(),[NaN,0,0],[0,1,0],'hand',10));});

// Exercise the actual UI controllers in a DOM/canvas test adapter (not visual browser QA).
function app(saved,failWrites=false){let now=0,raf,storage=new Map(),registered=[],events={};if(saved)storage.set('sand-digger.save.v1',saved);let elems={};const cx=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(t,p)=>p in t?t[p]:()=>{},set:(t,p,v)=>(t[p]=v,true)});
function el(id){return elems[id]??=( {id,style:{},dataset:{},value:'',checked:id==='sfx',open:false,textContent:'',classList:{add(){},remove(){},toggle(){}},listeners:{},setAttribute(){},addEventListener(type,fn){this.listeners[type]=fn;},getBoundingClientRect:()=>({left:0,top:0,width:900,height:700}),getContext:()=>cx,setPointerCapture(){},showModal(){this.open=true;},close(){this.open=false;}});}
const buttons=['brush','finger','hand'].map(t=>{const b=el(t);b.dataset.tool=t;return b;});
const doc={getElementById:el,querySelectorAll:()=>buttons,querySelector:()=>Object.values(elems).find(e=>e.open),addEventListener:(k,f)=>events[k]=f,modelContext:{registerTool:t=>registered.push(t)}};
const box={SandEngine:E,document:doc,performance:{now:()=>now},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(failWrites)throw Error('Disk full');storage.set(k,v);}},console:{log:console.log,warn(){},error(){}},window:{addEventListener(){}},ResizeObserver:class{constructor(f){this.f=f;}observe(){this.f();}},devicePixelRatio:1,requestAnimationFrame:f=>raf=f,setTimeout:()=>{},AbortController,Math,Uint8Array};vm.runInNewContext(fs.readFileSync(__dirname+'/dist/game.js','utf8'),box);
return {el,storage,registered,frame(ms=17){now+=ms;raf(now);},pointer(type,x=450,y=350){el('game').listeners[type]({clientX:x,clientY:y,pointerId:1,button:0});},get(){return E.decode(storage.get('sand-digger.save.v1'));}};}
test('UI startup, render and valid tool selection execute',()=>{let a=app();a.frame();const select=a.registered.find(t=>t.name==='select_sand_tool');select.execute({tool:'brush'});const read=a.registered.find(t=>t.name==='read_sand_match');assert.equal(read.execute().tool,'brush');assert.throws(()=>select.execute({tool:'laser'}));assert.equal(read.execute().tool,'brush');});
test('A real pointer action harvests and switches the active player',()=>{let a=app();a.frame();a.pointer('pointerdown');a.pointer('pointerup');for(let i=0;i<130;i++)a.frame();let s=a.get();assert(s.scores[0]>0);assert.equal(s.player,1);});
test('UI cancelled touch rolls back to confirmed state',()=>{let a=app(E.encode(E.create()));a.pointer('pointerdown');a.pointer('pointercancel');a.frame(16000);assert.deepEqual(a.get().scores,[0,0]);assert.equal(a.get().player,0);});
test('UI save failure rolls an action back without reporting success',()=>{let a=app(E.encode(E.create()),true);a.pointer('pointerdown');a.pointer('pointerup');for(let i=0;i<130;i++)a.frame();const read=a.registered.find(t=>t.name==='read_sand_match');assert.deepEqual(Array.from(read.execute().scores),[0,0]);assert.equal(read.execute().player,1);assert(a.el('saveStatus').textContent.includes('실패'));});
test('Corrupt save is preserved until explicit new-game replacement',()=>{let a=app('broken');a.frame(16000);assert.equal(a.storage.get('sand-digger.save.v1'),'broken');});
console.log(`\n${passed} tests passed. UI adapter tests do not verify visual layout or mobile hardware.`);
